"""Real bytes for the seeded files (§20).

Before MinIO existed, a seeded file was a row with a `storage_key` pointing at
nothing — and the comment in `content.py` said as much. A file manager whose
every download fails is not a demonstration of a file manager, so the seed now
writes an actual object for each file it creates.

**Every format here is one this module can genuinely produce.** A `.xlsx` whose
bytes are plain text is not a spreadsheet: it is a file that looks fine in a
list and fails in the application the reader opens it with, which is worse than
not offering it. So the catalogue was narrowed to the formats a generator can
write honestly — text, markdown, CSV, JSON, logs, SVG, and the two binary
formats small enough to emit by hand.

The content is generated from the file's own name and folder, so a downloaded
document is *about* the thing the list said it was.
"""

from __future__ import annotations

import json
import zlib
#: A 1×1 transparent PNG, assembled rather than pasted as base64 so the chunk
#: structure is visible and the CRCs are computed rather than trusted.
def _png() -> bytes:
    def chunk(kind: bytes, payload: bytes) -> bytes:
        body = kind + payload
        return (
            len(payload).to_bytes(4, "big")
            + body
            + zlib.crc32(body).to_bytes(4, "big")
        )

    header = (1).to_bytes(4, "big") + (1).to_bytes(4, "big") + bytes([8, 6, 0, 0, 0])
    pixel = zlib.compress(b"\x00\x00\x00\x00\x00")
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", pixel)
        + chunk(b"IEND", b"")
    )


def _pdf(title: str, body: str) -> bytes:
    """A minimal, valid single-page PDF. Opens in a reader; says what it is."""
    text = f"BT /F1 14 Tf 56 720 Td ({_pdf_escape(title)}) Tj ET\n"
    text += f"BT /F1 10 Tf 56 690 Td ({_pdf_escape(body)}) Tj ET"
    stream = text.encode("latin-1", "replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for number, body_bytes in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body_bytes + b"\nendobj\n"

    start = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{start}\n".encode()
        + b"%%EOF\n"
    )
    return bytes(out)


def _pdf_escape(text: str) -> str:
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def body_for(name: str, extension: str, folder: str, preview: str | None) -> bytes:
    """The bytes one seeded file should contain.

    Generated from the file's own name and folder, so a downloaded document is
    about the thing the list said it was — a demo whose files all contain
    "lorem ipsum" teaches nobody whether the preview pane works.
    """
    heading = name.rsplit(".", 1)[0]
    note = preview or f"Prepared for {folder}. Generated by the Nucleus seed."

    if extension == "json":
        return json.dumps(
            {"title": heading, "folder": folder, "note": note, "generated_by": "nucleus-seed"},
            indent=2,
        ).encode()

    if extension == "csv":
        rows = ["period,opened,closed,carried"]
        rows += [f"2026-{month:02d},{month * 7},{month * 5},{month * 2}" for month in range(1, 13)]
        return "\n".join(rows).encode()

    if extension == "log":
        lines = [
            f"2026-03-{day:02d}T09:00:00Z INFO  {heading}: reconciliation started"
            for day in range(1, 9)
        ]
        lines.append("2026-03-09T09:00:00Z WARN  three records carried forward")
        return "\n".join(lines).encode()

    if extension == "md":
        return (
            f"# {heading}\n\n{note}\n\n"
            "## Scope\n\nEverything in this document is generated demo content.\n"
        ).encode()

    if extension == "svg":
        return (
            '<svg xmlns="http://www.w3.org/2000/svg" width="240" height="80">'
            '<rect width="240" height="80" fill="#eeeefc"/>'
            f'<text x="16" y="46" font-family="sans-serif" font-size="14" fill="#332f96">'
            f"{heading[:26]}</text></svg>"
        ).encode()

    if extension == "png":
        return _png()

    if extension == "pdf":
        return _pdf(heading, note)

    return f"{heading}\n\n{note}\n".encode()


def materialise(session, store) -> dict[str, int]:
    """Write the bytes for every ready file that has none, and correct its size.

    Idempotent: a file whose object is already there is left alone, so this is
    safe to run on every seed and on an existing database that predates object
    storage.
    """
    from sqlalchemy import select

    from src.models.content import FileObject, Folder

    written = 0
    skipped = 0

    rows = session.execute(
        select(FileObject, Folder.path)
        .outerjoin(Folder, Folder.id == FileObject.folder_id)
        .where(FileObject.deleted_at.is_(None), FileObject.status == "READY")
    ).all()

    for row, folder_path in rows:
        if not row.storage_key:
            skipped += 1
            continue
        if store.stat(row.storage_key) is not None:
            skipped += 1
            continue

        body = body_for(
            row.name, (row.extension or "").lower(), folder_path or "the library", row.preview_text
        )
        stored = store.put(
            row.storage_key, body, content_type=row.mime_type or "application/octet-stream"
        )
        # The row now describes the object rather than a number the seed made
        # up: a file manager that reports 15 MB and downloads 400 bytes is one
        # nobody trusts twice.
        row.size_bytes = stored.size_bytes
        row.checksum = stored.checksum
        written += 1

    session.flush()
    return {"written": written, "already_present": skipped}
