"""report documents

Revision: 06bc69c46cd4
Parent:   1845cad360f1
Created:  2026-09-10 17:50:35.761236+00:00
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06bc69c46cd4'
down_revision: str | None = '1845cad360f1'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('page', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_rendered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('render_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_documents_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_report_documents_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_documents'))
    )
    op.create_index(op.f('ix_report_documents_created_at'), 'report_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_documents_deleted_at'), 'report_documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_report_documents_last_rendered_at'), 'report_documents', ['last_rendered_at'], unique=False)
    op.create_index(op.f('ix_report_documents_name'), 'report_documents', ['name'], unique=False)
    op.create_index(op.f('ix_report_documents_organization_id'), 'report_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_documents_owner_id'), 'report_documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_report_documents_scope'), 'report_documents', ['scope'], unique=False)
    op.create_index(op.f('ix_report_documents_slug'), 'report_documents', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_documents_slug'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_scope'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_owner_id'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_organization_id'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_name'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_last_rendered_at'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_deleted_at'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_created_at'), table_name='report_documents')
    op.drop_table('report_documents')
    # ### end Alembic commands ###
